### ISSUE TITLE
Cannot activate despite build-tools installed

### ISSUE THREAD

**Issue by gianted** [dsanders11/vscode-electron-build-tools#21]
Hi, build-tools up-to-date, extension installed from marketplace, I cannot figure out to have a working extension (I see only "Welcome" and "Help" tabs). The other tabs sometimes are initially shown but suddenly disappear.

Tried with the suggested [troubleshooting](https://github.com/dsanders11/vscode-electron-build-tools/wiki/Troubleshooting) but without success (also tried to sym-link "electron-build-tools" to the "e" executable).

Please help, thanks.

Electron Build Tools: v.0.5.0
VScode: October 2020 (version 1.51)
macOS Big Sur v.11.0.1

**Comment by dsanders11** [comment]
Thanks for filing the issue. I haven't had a chance to test the extension under MacOS, so there may just be something simple here.

Can you run `which electron-build-tools` in a terminal inside VS Code to check that the executable can be found?

Also, if an error is occurring it should be logged, so you could check the output panel, which is found under View -> Output, and in the dropdown selector there should be "Electron Build Tools" listed.

**Comment by gianted** [comment]
```
gianted@itraws192:~/src/electron/next-responsive
$ which electron-build-tools
gianted@itraws192:~/src/electron/next-responsive
$ which e
/Users/gianted/.nvm/versions/node/v14.15.0/bin/e
```

As I told before, electron-build-tools is reachable only if symlinked to ‘e’ executable...

```
gianted@itraws192:~/src/electron/next-responsive
$ ln -s /Users/gianted/.nvm/versions/node/v14.15.0/bin/e /Users/gianted/.nvm/versions/node/v14.15.0/bin/electron-build-tools
```
```
gianted@itraws192:~/src/electron/next-responsive
$ which electron-build-tools
/Users/gianted/.nvm/versions/node/v14.15.0/bin/electron-build-tools
```
And no error logged in Output

<img width="1440" alt="ebt_output" src="https://user-images.githubusercontent.com/34244388/101287691-20fd0c00-37f2-11eb-90b3-834d63e599ce.png">

Sorry, maybe I don't understand before the purpose of this extension: by reading again the description, it seems designed to working on the _entire_ Electron project, isn't it?

I'm only searching for an helper extension to speed-up the development life-cycle of some Electron-based projects.

**Comment by dsanders11** [comment]
> Sorry, maybe I don't understand before the purpose of this extension: by reading again the description, it seems designed to working on the entire Electron project, isn't it?

Yes, it is for working with the Electron codebase - building Electron from source. The same with Electron `build-tools`, that is used for building Electron from source, not for regular Electron projects.

**Comment by gianted** [comment]
However, thanks for your time David... :-)
